### PR TITLE
bugfix: flaky tests caused by accessDenied test

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Test what will happen if I remove accessDenied test.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-yinzi** [comment]
@edalex-ian could you please run these tests again several times?

**Comment by edalex-ian** [comment]
Rerun started.

**Comment by edalex-yinzi** [comment]
Passed again!

**Comment by edalex-yinzi** [comment]
@After is not worked...

**Comment by edalex-ian** [comment]
Okay, as discussed, a couple of things:

- The report you're looking at that shows the accessDenied test as the last test to pass is just the summary report and not the actual execution order. So chasing that is a red herring, key is that you need to attempt to run the test _many_ _many_ times locally and see if you can replicate at all - indeed also under slower conditions.
- The @After you've chosen is for jUnit, we're testing with TestNG.

With that in mind, I'll close this one off for you.

**Pull request closed without merging**
