### PR TITLE
the great selection session styling commit

### PR DESCRIPTION
**Pull request by mrblippy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [ ] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Covers all things selection session related (structured and old skool selectOrAdd selection session)

moodle item summary
moodle search
moodle select items
oeq selection session
oeq selection session2

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
Scrolling down the selection session (both via equella and via moodle) causes the options at the top of the page to come down with you. If this is intended, then the background to the options bar should come with it.

**Comment by SammyIsConfused** [comment]
In IE11, the window sizing doesn't work correctly via moodle. This doesn't apply to the in-equella selection session.
image

**Comment by SammyIsConfused** [comment]
The "reject task" dialog dropdown needs a min-width. 
image

**Comment by SammyIsConfused** [comment]
image
Just one more thing; a little bit of a margin between the top of the selection session and the content would be good, right now things are getting chopped off by the bar at the top.

**Comment by mrblippy** [comment]
@SammyIsConfused all of your issues have now been fixed. I am going to merge this back into the feature branch

**Pull request merged**
