### PR TITLE
Settings styling

### PR DESCRIPTION
**Pull request by mrblippy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change

https://github.com/openequella/openEQUELLA/issues/1184

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
image
Searching and content indexing page needs fixing up, namely the sliders.

**Comment by SammyIsConfused** [comment]
The alignment on the filters on the dashboard admin settings page needs fixing 
image

**Comment by SammyIsConfused** [comment]
image
The search bar on the Course page is a little off.

**Comment by SammyIsConfused** [comment]
image
IE11 specific: This is a pretty obscure one. Go to Add User Content Quota, then select Users, then Other. The IP address settings are all mushed.

**Comment by SammyIsConfused** [comment]
image
The script editor seems to be missing.

**Comment by SammyIsConfused** [comment]
On the "Create new LTI consumer" page, the "other roles" helper text is partially obscured.

**Comment by SammyIsConfused** [comment]
image
Reports page is a little off.

**Comment by PenghaiZhang** [comment]
After discussions with @edalex-ian we've merged this branch in so that we can do a full sweep of manual testing (thanks @SammyIsConfused ) and commence work on getting tests running again. We'll capture the results of the testing elsewhere and start work on fixing them too.

**Pull request merged**
