### PR TITLE
feat(rest-module): add support for includeAttachments param of search2

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Short and simple, this updates the REST Module (oeq-ts-rest-api) to match the back-end changes for `includeAttachments` and `attachmentCount`.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by PenghaiZhang — COMMENTED** [review]
Looks like `attachmentCount` is missing some type definitions.

**Review by PenghaiZhang — COMMENTED** [review]
Looks like `attachmentCount` i missing in some mock data.

**Comment by edalex-ian** [comment]
Gah, of course. I only ran the tests for the REST module. :disappointed:

**Comment by edalex-ian** [comment]
Just flaked on two known flakies:

- com.tle.webtests.test.webservices.rest.ItemApiEditTest
- com.tle.webtests.test.myresources.MyResourcesTest

Should be good to go once review done.

**Review by PenghaiZhang — APPROVED** [review]
LGTM!

**Pull request merged**
