### PR TITLE
fix: update dependency com.thoughtworks.xstream:xstream to v1…

### PR DESCRIPTION
**Pull request by edalex-yinzi**
To fix #4547.

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Since version 20, `The WildcardTypePermission allows by default no longer anonymous class types`.
https://x-stream.github.io/changes.html

I have updated the xstream config.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-yinzi** [comment]
I can't replicate it locally, so I create a draft PR to test GitHub action here.

**Comment by edalex-yinzi** [comment]
Hi @edalex-ian and @PenghaiZhang. I am not sure if these changes also need some migration code, like some actions on DB.

**Comment by edalex-yinzi** [comment]
Or should I just set xstream to accept the anonymous class? It will be simpler.

**Comment by edalex-yinzi** [comment]
Import test failed.

**Comment by edalex-yinzi** [comment]
As discussed, letting xstream allows anonymous class type should be a better solution here since we don't want to change the institution files.

**Review by edalex-ian — APPROVED** [review]
Thanks @edalex-yinzi , and I also like that this is only enabling it a defined area. So any newer work will hopefully avoid this.

**Pull request merged**
