### PR TITLE
chore: test ci for flaky tests

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [ ] the [contributor license agreement][] is signed
- [ ] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-yinzi** [comment]
OK looks good.

**Comment by edalex-yinzi** [comment]
2

**Comment by edalex-yinzi** [comment]
3

**Comment by edalex-yinzi** [comment]
Maybe the issue is the test will be affected by other tests; I will bring another test back.

**Comment by edalex-yinzi** [comment]
1

**Comment by edalex-yinzi** [comment]
2

**Comment by edalex-yinzi** [comment]
It looks like FavouritesPowerSearchIntegration has been fixed.

**Comment by edalex-yinzi** [comment]
1

**Comment by edalex-yinzi** [comment]
Interesting, so after I added the screenshot, the portal test became stable.

**Comment by edalex-ian** [comment]
> Interesting, so after I added the screenshot, the portal test became stable.

Makes sense, as these flaky issues seem to all be timing based. So add something in that significantly alters duration (screenshots) and then you change the timing environment.

**Comment by edalex-yinzi** [comment]
:sob:

**Comment by edalex-yinzi** [comment]
Adding screenshots really stabilized the tests a lot... I think I should add explicit waits to fix the tests.

**Comment by edalex-ian** [comment]
> Adding screenshots really stabilized the tests a lot... I think I should add explicit waits to fix the tests.

Although an easy way to fix this kind of issue, it's an approach that is considered a big NO! It's just a temporary fix at best, at worst it can add more unknowns - as it signals a thread switch.

**Comment by edalex-yinzi** [comment]
Okay at least those timneout issues has been solved. Now we only have `java.lang.AssertionError: expected [true] but found [false]` .

**Comment by edalex-ian** [comment]
So this is superseded by #5023 ?

**Comment by edalex-yinzi** [comment]
> So this is superseded by #5023 ?

Yes. Closed.

**Pull request closed without merging**
