### PR TITLE
styling of item summary page, includes zebra tables, comment and atta…

### PR DESCRIPTION
**Pull request by mrblippy**
##### Description of change

This pr covers  all things related to the item summary page. Screenshots below:
summary 2
summary activations
summary mod history
summary versions
summary 1

Hopefully that covers it all, and I haven't forgotten any areas

https://github.com/openequella/openEQUELLA/issues/1184

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
The "Remove favourites" button is not styles, renders as invisible until hovered upon.

**Comment by SammyIsConfused** [comment]
image
The padding near to checkboxes should probably be increased.

**Comment by SammyIsConfused** [comment]
Would it be possible to align the "ADD COMMENT" button with the edge of the comment text box?
image

**Comment by SammyIsConfused** [comment]
The padding on the radio buttons could be increased, too. 
image

**Comment by SammyIsConfused** [comment]
More checkbox padding 
image

**Comment by SammyIsConfused** [comment]
image
 when there are no schema transforms in the drop down it does this. Might need a min-width setting.

**Comment by SammyIsConfused** [comment]
All seems to look and act the same in all four browsers, even IE11. Once we have those few visual tweaks we should be good to go!

**Comment by mrblippy** [comment]
All of your feedback has been addressed @SammyIsConfused. Merging the changes back into feature branch

**Pull request merged**
