### PR TITLE
fix(test): testBulkMetadataEdit timeout issue

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

First commit, add retryTest annotation.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by edalex-ian — APPROVED** [review]
Thanks @edalex-yinzi 

I see GHA timed out again on SearchPage.test.tsx so I've restarted it. But CodeBuild was happy so we should be good to merge soon.

**Comment by PenghaiZhang** [comment]
This flaky test only fails on GHA so I suggest we retry GHA builds a couple more times.  And I have restarted again due to SearchPage test timeout.

**Comment by edalex-ian** [comment]
Good plan, there's one successful run, going for run number 2 now.

**Comment by edalex-ian** [comment]
There was a failure, but on other flaky tests:

image

Going for run number 3 now.

**Comment by edalex-ian** [comment]
Hmmm, last re-run failed on a new one: `testChangeResultOrder` in `com.tle.webtests.test.searching.SearchSettingsTest`. This is not in my list of flaky tests. Will rerun one more time to be sure.

**Comment by edalex-ian** [comment]
Excellent, just a fail on ol' flaky `AdvancedScriptControlTests`. Let's merge.

**Pull request merged**
