### PR TITLE
EBP: Fix position of right navigation pane

### PR DESCRIPTION
**Pull request by SammyIsConfused**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
#1983 
Also, fix up some strange test behaviour in AdvancedScriptControlTests. Caused by advanced scripting directly injecting `<pre>` tags which would get very long and stretch out the contribution wizard panel. Swapping these for `<span>` fixed the issue. 
image

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Heya @SammyIsConfused 

Is this to address this:

image-2020-07-22-17-30-46-035

**Comment by SammyIsConfused** [comment]
> Heya @SammyIsConfused
> 
> Is this to address this:
> 
> image-2020-07-22-17-30-46-035

Yup!

**Comment by PenghaiZhang** [comment]
I will discuss this with Sam tomorrow morning in the office.

**Comment by PenghaiZhang** [comment]
OK we also need to update `getAscMessage` and maybe `getAscMessage1`.

**Pull request merged**
