### PR TITLE
Make MimeTypesTest more robust

### PR DESCRIPTION
**Pull request by SammyIsConfused**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change
MimeTypesTest has been giving us a lot of problems in GHA as of late. The problem was caused by a missing wait in getIcon() which was fixed in a previous PR. Turns out there were more missing waits after this happens, namely the one in 903461d before clicking restoreIcon `(id="mei_ri")`. I've also gone through MimeEditorPage.java adding missing waits before clicking and sending text to elements, for good measure (eb6be5e).
Before making those changes I was able to replicate the test failure locally by disabling caching and throttling the speed of my test browser and retrying a few times since it's intermittent. Testing with these changes I have yet to see it happen. Hopefully CI can verify that.    

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Just as I was about to start reviewing, the Legacy mode test failed. :disappointed: 

I wont review just yet, let me know when you've had a look. (Don't forget, you can download the screenshots etc. from the GHA results.)

**Comment by SammyIsConfused** [comment]
Gah! Still a problem with MimeTypesTest. How frustrating. Apparently it timed out waiting, so there must be something wrong still.

**Comment by SammyIsConfused** [comment]
Okay it looks like it's attempting to upload the icon and failing silently, which is why the problem occurs on waiting for the new icon. :disappointed: Locally the upload happens fine so I don't know what's going on. 
Attempting to fix up now.

**Comment by edalex-ian** [comment]
When looking at the logs in #2571 it occurred to me that this is an area that recently also had EBP updates made. In the past we've had issues due to screen size differences to CodeBuild, is it possible that's the issue here?

**Comment by SammyIsConfused** [comment]
> When looking at the logs in #2571 it occurred to me that this is an area that recently also had EBP updates made. In the past we've had issues due to screen size differences to CodeBuild, is it possible that's the issue here?

Nope unfortunately - since it's still happening in this branch and we have a scrollToElement in here which deliberately scrolls it into view.

**Comment by SammyIsConfused** [comment]
Well hey, that's one green build. Let's try that again.

**Review by ChristianMurphy — APPROVED** [review]

**Comment by PenghaiZhang** [comment]
The build for 846e5cbd5b2a5b58fbde3205caffb0b241477963 failed on `FileIndexingTest` which I never saw before. But it's good to see `MimeTypesTest` pass again. I will give one more try.

**Comment by PenghaiZhang** [comment]
Is there any further work required in this PR ? If no, it's good to merge develop to this branch and run all the builds again.

**Pull request closed without merging**
