### PR TITLE
chore(deps): update dependency eslint-plugin-prettier to v5 

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
To fix #4845.

Update `prettier` to v3.
Format all ts files.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Need to run eslint format:

image

**Comment by edalex-yinzi** [comment]
Too many conflicts after merging gitlab branch. I probably will do another force push.

**Comment by edalex-yinzi** [comment]
Ah, I forgot to merge develop.

**Comment by edalex-yinzi** [comment]
Flaky test `multipleAttachmentSections`.

**Comment by edalex-ian** [comment]
hmmmm, what's happened here @edalex-yinzi ? Before it failed on a handful of files, but suddenly you've gone and change 289 files!!

And I'm not sure are about the superfluous commas in the function definitions..... :thinking:

**Comment by edalex-yinzi** [comment]
> hmmmm, what's happened here @edalex-yinzi ? Before it failed on a handful of files, but suddenly you've gone and change 289 files!!
> 
> And I'm not sure are about the superfluous commas in the function definitions..... 🤔

`prettier` is updated from v2 to v3, it might contain new rules. All these files are updated by `npm run format`.

**Comment by edalex-yinzi** [comment]
I will do another force push and try format again.

**Comment by edalex-yinzi** [comment]
Breaking changes on v3:

image

**Comment by edalex-ian** [comment]
Heya @edalex-yinzi ,

So basically this is ready for review, we just need to decide if we're happy with the extra commas. Is that correct?

Please address conflicts.

**Comment by edalex-yinzi** [comment]
> Heya @edalex-yinzi ,
> 
> So basically this is ready for review, we just need to decide if we're happy with the extra commas. Is that correct?
> 
> Please address conflicts.

Yes.

**Comment by PenghaiZhang** [comment]
I am not quite used to so many trailing commas, but I guess this has become the standard.

**Comment by PenghaiZhang** [comment]
Hi @edalex-yinzi , can you resolve the conflict and merge develop to your branch and try again ?

**Comment by edalex-yinzi** [comment]
> Hi @edalex-yinzi , can you resolve the conflict and merge develop to your branch and try again ?

Sure.

**Comment by PenghaiZhang** [comment]
Finally the build is OK. Do you want to review again @edalex-ian  ?

**Comment by edalex-ian** [comment]
The only thing I have @PenghaiZhang , is do we want to keep all those commas? Or should we tweak the rules like we've done for others?

The specific change is here (as well as how to disable it): https://prettier.io/blog/2023/07/05/3.0.0.html#change-the-default-value-for-trailingcomma-to-all-11479httpsgithubcomprettierprettierpull11479-by-fiskerhttpsgithubcomfisker-13143httpsgithubcomprettierprettierpull13143-by-sosukesuzukihttpsgithubcomsosukesuzuki

Why have trailing commas: 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas
- https://github.com/airbnb/javascript#commas--dangling
- https://blog.logrocket.com/best-practices-using-trailing-commas-javascript/

So with that it feels like it's the idiomatic style JS peeps want and hence prettier are aligning with that. So perhaps we should just go with it.

What do you think? If you're happy, feel free to merge. If you'd like to discuss, let me know.

**Comment by PenghaiZhang** [comment]
> The only thing I have @PenghaiZhang , is do we want to keep all those commas? Or should we tweak the rules like we've done for others?
> 
> The specific change is here (as well as how to disable it): https://prettier.io/blog/2023/07/05/3.0.0.html#change-the-default-value-for-trailingcomma-to-all-11479httpsgithubcomprettierprettierpull11479-by-fiskerhttpsgithubcomfisker-13143httpsgithubcomprettierprettierpull13143-by-sosukesuzukihttpsgithubcomsosukesuzuki
> 
> Why have trailing commas:
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas
> * https://github.com/airbnb/javascript#commas--dangling
> * https://blog.logrocket.com/best-practices-using-trailing-commas-javascript/
> 
> So with that it feels like it's the idiomatic style JS peeps want and hence prettier are aligning with that. So perhaps we should just go with it.
> 
> What do you think? If you're happy, feel free to merge. If you'd like to discuss, let me know.

Although I do not like these trailing commas, maybe it's just because I am not used to it. And also because this has become the idiomatic style, I think it's better to accept it now so that we would not have too much trouble in the future when these commas become more important.

**Pull request merged**
