### PR TITLE
build (github): change order or node dep install

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
~~- [ ] tests are included~~
~~- [ ] screenshots are included showing significant UI changes~~
~~- [ ] documentation is changed or added~~

##### Description of change

Need to install the root node dependencies before the others, as the new io-ts code-gen relies on ESLint being installed from the root first.

An alternative could be to try and get the oeq-ts-rest-api to install ESLint before it starts the codegen, however this is probably easier (and all is working on the internal Edalex build - due to this order difference).

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
After making that second commit, I now wonder if ESLint should be a dependency down in the codegen package.json file. It does after all depend on it, so why not add it there.

Let me know what you think @PenghaiZhang

**Review by PenghaiZhang — APPROVED** [review]
LGTM!

**Comment by PenghaiZhang** [comment]
> After making that second commit, I now wonder if ESLint should be a dependency down in the codegen package.json file. It does after all depend on it, so why not add it there.
> 
> Let me know what you think @PenghaiZhang

I think that's OK, but we end up having `eslint` in both `oeq-ts-rest-api` and `io-ts-gen`, which may be confusing.

**Comment by edalex-ian** [comment]
> > After making that second commit, I now wonder if ESLint should be a dependency down in the codegen package.json file. It does after all depend on it, so why not add it there.
> > Let me know what you think @PenghaiZhang
> 
> I think that's OK, but we end up having `eslint` in both `oeq-ts-rest-api` and `io-ts-gen`, which may be confusing.

But it already has some of it's own ESLint setup as the intention is to still split this out to it's own module for adopters to be able to use for integrations etc.

**Comment by edalex-ian** [comment]
Ah, and now I see the issue is more pervasive. I think that might be what we need to do.

**Comment by PenghaiZhang** [comment]
> Ah, and now I see the issue is more pervasive. I think that might be what we need to do.

Agreed. Let's do that.

**Comment by edalex-ian** [comment]
Resolved with #4679

**Pull request closed without merging**
