### PR TITLE
#1214 Upgrade Spring to 3.2.18-RELEASE

### PR DESCRIPTION
**Pull request by cbeach47**
### Checklist
- [X] the [contributor license agreement][] is signed
- [X] commit message follows [commit guidelines][]

##### Description of change
As a pre-req to #1214 / #909 .

Need to upgrade Spring, then CXF, then Tika.

Going to upgrade all three to see if it's feasible and if there are any more dependencies that will be caught up in this effort.  Depending on the scope of changes needed, I may back off and commit one at a time, or just handle all three.

### CODE REVIEW

**Comment by cbeach47** [comment]
Interesting - booting up oEQ is failing with the following.  I added the `@Transactional` to the `findAllByCriteria` methods, but no joy.



```
17:29:16,311 ERROR [MigrationGlobalTask] Error checking for migrations on system schema
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
	at org.springframework.orm.hibernate3.HibernateTemplate.getSession(HibernateTemplate.java:469)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:393)
	at com.tle.core.hibernate.dao.AbstractHibernateDao$1.doExecute(AbstractHibernateDao.java:53)
	at org.springframework.orm.hibernate3.HibernateTemplate.executeFind(HibernateTemplate.java:344)
	at com.tle.core.hibernate.dao.GenericDaoImpl.findAllByCriteria(GenericDaoImpl.java:252)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at com.tle.core.hibernate.dao.GenericDaoImpl.findAllByCriteria(GenericDaoImpl.java:234)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at com.tle.core.hibernate.dao.GenericDaoImpl.findAllByCriteria(GenericDaoImpl.java:221)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at com.tle.core.system.impl.DatabaseSchemaDaoImpl.enumerate(DatabaseSchemaDaoImpl.java:42)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at com.tle.core.migration.impl.MigrationGlobalTask.checkSystemSchema(MigrationGlobalTask.java:321)
	at com.tle.core.migration.impl.MigrationGlobalTask.init(MigrationGlobalTask.java:104)
	at com.tle.core.services.impl.AlwaysRunningTask.call(AlwaysRunningTask.java:36)
	at com.tle.core.services.impl.AlwaysRunningTask.call(AlwaysRunningTask.java:27)
	at com.tle.core.services.impl.LocalTaskServiceImpl$LocalTask.run(LocalTaskServiceImpl.java:485)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
	at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:64)
	at org.hibernate.impl.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:687)
	at org.springframework.orm.hibernate3.HibernateTemplate.getSession(HibernateTemplate.java:466)
	... 29 more
```

**Comment by cbeach47** [comment]
@edalex-ian - off the top of your head, do you have any ideas on a path forward to get Spring 3 working?

According to https://mvnrepository.com/artifact/org.springframework/spring-orm/3.2.18.RELEASE , hibernate might also need to be upgraded, which I was trying to avoid.

I'll keep digging into this tomorrow.

**Comment by edalex-ian** [comment]
Ahhh, good point. That's one big bit of Spring oEQ uses - `HibernateTemplate`s.

It seems like the hibernate version in `Source/Plugins/Generic/org.hibernate/build.sbt` should be okay though. But maybe some of the other deps in that specific build.sbt. :thinking:

It's interesting the comments about Spring 3 and the move away from templates: https://www.baeldung.com/persistence-layer-with-spring-and-hibernate

**Comment by cbeach47** [comment]
Due to widen scope of the effort, I'm going to set this aside for now.

**Pull request closed without merging**
