### PR TITLE
Blackboard REST MVP

### PR DESCRIPTION
**Pull request by cbeach47**
### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
  - autotests not setup for Blackboard integration tests
- [x] screenshots are included showing significant UI changes
- [x] documentation is changed or added
  - Via https://github.com/openequella/openequella.github.io/issues/55

##### Description of change

Part of the Blackboard REST MVP ( looking to keep the number of commits into Dev small since I'll likely need to backport this into 2019.1 / 2019.2 / 2020.0 ) ( https://github.com/openequella/openEQUELLA/issues?q=is%3Aopen+label%3A%22Integration+-+Bb+LTI%2FREST%22+milestone%3A2020.2 ):

Included:
- Blackboard 3-Legged-OAuth now working ( #821 )
- Courses by user retrieve (instead of all courses) ( #846 )
- Blackboard rate limit stats exposed via the audit logs and log4j logs ( #853 )

Need to finish out:
- Blackboard course caching improvement ( #819 )
- General clean up due to D2L code copy
- General testing

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Looks like your pre-commit hooks might not be setup. The various failures were code format checking:

```
> find . -name '*.java' | xargs google-java-format -n --set-exit-if-changed
./Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/blackboard/editor/BlackboardRESTConnectorEditor.java
./Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/blackboard/servlet/BlackboardRestOauthSignonServlet.java
./Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/dialog/LMSAuthDialog.java
./Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/BlackboardRestUserContext.java
./Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/BlackboardRestAppContext.java
./Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/BlackboardRESTConnectorConstants.java
./Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
./Source/Plugins/Core/com.equella.core/src/com/tle/core/auditlog/impl/AuditLogServiceImpl.java
```

That's normally handled by the pre-commit hooks. Make sure you've run a `npm install` in the root of you clone.

**Comment by cbeach47** [comment]
@edalex-ian - turns out node and git were back-leveled causing the pre-commit hooks to not fire.

**Comment by edalex-ian** [comment]
No worries @cbeach47 , I see you've sorted it now.

The failing test in GitHub is being fixed in #1757 - strange it didn't fail on CodeBuild though. :thinking:

**Comment by cbeach47** [comment]
Looks like the build error is an unrelated UI issue that is present in `develop` as well.

**Comment by cbeach47** [comment]
In the attempt to help resolve the build issues by rebasing / merging `develop` into this branch with the latest from upstream, git brought over all the commits.  I'm going to close and recreate this PR.

**Pull request closed without merging**
