### PR TITLE
fix: FavouritesPowerSearchIntegration

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Wait for items before using findElements.

I have run the action twice in the draft MR with no failures.

let's see how things will go here.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-yinzi** [comment]
1

**Review by edalex-ian — APPROVED** [review]
LGTM thanks @edalex-yinzi 

If you get three good runs (i.e. with no `FavouritesPowerSearchIntegration` failures) then please merge.

**Comment by edalex-yinzi** [comment]
Failed. :cry:

**Comment by edalex-yinzi** [comment]
1

**Comment by edalex-yinzi** [comment]
2

**Comment by edalex-yinzi** [comment]
3

**Comment by edalex-yinzi** [comment]
1

**Comment by edalex-yinzi** [comment]
3

**Review by edalex-ian — APPROVED** [review]
Thanks @edalex-yinzi 

Change looks to make sense, and I'm keen to try it out. Let's merge after the next run (unless it fails on `FavouritesPowerSearchIntegration`).

**Comment by edalex-ian** [comment]
Cool, last failure was PortalsTest (which we really still need to get sorted) so let's merge.

**Pull request merged**
