### PR TITLE
CI: Upgrade GHA artefact upload action

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change

Version 2 is now out of preview and has some fixes, so time to start using the official release. Hopefully will also address the upload issues as mentioned in #1792 .

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
> ##### Checklist
> * [x]  the [contributor license agreement](https://www.apereo.org/node/676) is signed
> * [x]  commit message follows [commit guidelines](https://chris.beams.io/posts/git-commit/)
> 
> ##### Description of change
> Version 2 is now out of preview and has some fixes, so time to start using the official release. Hopefully will also address the upload issues as mentioned in #1792 .

The latest version 2.0.1  has this feature: `Now if a file fails to upload after hitting a retry limit, any remaining uploads stop and the step fails`. I think this can fix the upload issues as mentioned in #1792 .

**Comment by edalex-ian** [comment]
Nicely spotted @PenghaiZhang !

If I understand how the versioning works with GHA actions, it's just tags so indeed we have to ensure we explicitly state the version to match a tag. I've made that change, let's see how the build goes. :crossed_fingers:

**Comment by ChristianMurphy** [comment]
FWIW, Renovate can also help keep github actions up-to-date
https://github.com/renovatebot/renovate/tree/c5f51853c8447b327624ebc66ad1f6a1cdad7bd6/lib/manager/github-actions

But this isn't a part of the hosted service due to

> For security reasons, GitHub has blocked integrations/apps from editing GitHub Actions workflow files in any branch, so this only works on GitHub if using a Personal Access Token instead of using the WhiteSource Renovate app.

**Comment by edalex-ian** [comment]
Thanks @ChristianMurphy ! I was actually wondering about that the other day, but didn't have time to look it up. Will look into enabling that when it all stablises. :+1:

**Pull request merged**
