### PR TITLE
test: add eslint config create react app to checks

### PR DESCRIPTION
**Pull request by ChristianMurphy**
This eslint config is provided by the react team with a set of recommendations to make react apps run smoothly.

https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app

These recommendations are non-stylistic, focusing on things like the rule of hooks.

https://reactjs.org/docs/hooks-rules.html
https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks

These rules do not overlap with, or interfere with, the existing prettier code style.

### CODE REVIEW

**Comment by edalex-ian** [comment]
Heya @ChristianMurphy 

Love the idea of adding this in.

But on a more general note, I see your usage of [WIP] in the PR subject. Did you want us to add that WIP GitHub bot?

IS.

**Comment by ChristianMurphy** [comment]
I'd be fine with or without the bot.
Now that https://github.blog/2019-02-14-introducing-draft-pull-requests are a thing, the value of having WIP bot has gone down.

**Comment by PenghaiZhang** [comment]
I guess that Travis failed because this plugin has conflicts with how modulars are imported. For instance, in SearchCourse.tsx,  we use `import VisibilitySensor = require("react-visibility-sensor");`

**Comment by ChristianMurphy** [comment]
There are a few lint errors.
The import related one should be resolved by https://github.com/openequella/openEQUELLA/pull/1230

**Comment by ChristianMurphy** [comment]
@PenghaiZhang @edalex-ian lint errors are resolved

```
npm run check:tsx

> openequella@ check:tsx /home/developer/projects/OpenSource/openEquella
> cd Source/Plugins/Core/com.equella.core/js && eslint src tsrc --ext js,ts,tsx && cd ../../../../..


/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/src/Tools/GenLangStrings.js
  8:13  warning  'newOut' is assigned a value but never used  no-unused-vars

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/src/Uploads/UploadList.js
  3:12  warning  Expected '===' and instead saw '=='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/cloudcontrol/index.ts
  136:32  warning  Expected '===' and instead saw '=='  eqeqeq
  253:44  warning  Expected '!==' and instead saw '!='  eqeqeq
  256:51  warning  Expected '===' and instead saw '=='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderAddDialog.tsx
  61:13  warning  Expected '===' and instead saw '=='  eqeqeq
  64:58  warning  Expected '===' and instead saw '=='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/cloudprovider/CloudProviderListPage.tsx
  204:17  warning  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  205:24  warning  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/components/ConfirmDialog.tsx
  20:3  warning  Useless constructor  @typescript-eslint/no-useless-constructor

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/components/CourseSelect.tsx
  73:24  warning  Expected '!==' and instead saw '!='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/components/SettingsMenuContainer.tsx
  12:3  warning  Useless constructor  @typescript-eslint/no-useless-constructor

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/course/SearchCourse.tsx
   84:37  warning  Expected '===' and instead saw '=='  eqeqeq
  190:28  warning  Expected '===' and instead saw '=='  eqeqeq
  217:69  warning  Expected '!==' and instead saw '!='  eqeqeq
  256:52  warning  Expected '!==' and instead saw '!='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
  112:28  warning  Expected '===' and instead saw '=='                                                                                                           eqeqeq
  113:32  warning  Expected '===' and instead saw '=='                                                                                                           eqeqeq
  204:18  warning  eval can be harmful                                                                                                                           no-eval
  219:6   warning  React Hook React.useEffect has missing dependencies: 'stdSubmit' and 'submitCurrentForm'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  236:6   warning  React Hook React.useEffect has a missing dependency: 'submitCurrentForm'. Either include it or remove the dependency array                    react-hooks/exhaustive-deps
  266:45  warning  Expected '===' and instead saw '=='                                                                                                           eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/LoginNoticeConfigPage.tsx
  98:24  warning  Expected '!==' and instead saw '!='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PostLoginNoticeConfigurator.tsx
   49:31  warning  Expected '!==' and instead saw '!='  eqeqeq
   84:35  warning  Expected '!==' and instead saw '!='  eqeqeq
  155:40  warning  Expected '===' and instead saw '=='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/loginnotice/PreLoginNoticeConfigurator.tsx
   61:35  warning  Expected '===' and instead saw '=='  eqeqeq
  102:35  warning  Expected '!==' and instead saw '!='  eqeqeq
  116:38  warning  Expected '!==' and instead saw '!='  eqeqeq
  117:31  warning  Expected '!==' and instead saw '!='  eqeqeq
  118:33  warning  Expected '!==' and instead saw '!='  eqeqeq
  119:30  warning  Expected '!==' and instead saw '!='  eqeqeq
  166:49  warning  Expected '!==' and instead saw '!='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx
   74:8   warning  React Hook React.useEffect has a missing dependency: 'updateTemplate'. Either include it or remove the dependency array. If 'updateTemplate' changes too often, find the parent component that defines it and wrap that definition in useCallback              react-hooks/exhaustive-deps
   76:67  warning  React Hook React.useEffect has a missing dependency: 'setPreventNavigation'. Either include it or remove the dependency array. If 'setPreventNavigation' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
  123:8   warning  React Hook React.useEffect has a missing dependency: 'legacyContent'. Either include it or remove the dependency array                                                                                                                                         react-hooks/exhaustive-deps
  128:7   warning  React Hook React.useEffect has a missing dependency: 'legacyContent'. Either include it or remove the dependency array                                                                                                                                         react-hooks/exhaustive-deps

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
  314:6   warning  React Hook React.useEffect has a missing dependency: 'updateMetaTags'. Either include it or remove the dependency array              react-hooks/exhaustive-deps
  351:13  warning  Anchors must have content and the content must be accessible by a screen reader                                                      jsx-a11y/anchor-has-content
  372:20  warning  Expected '===' and instead saw '=='                                                                                                  eqeqeq
  397:13  warning  Anchors must have content and the content must be accessible by a screen reader                                                      jsx-a11y/anchor-has-content
  446:5   warning  React Hook React.useMemo has missing dependencies: 'classes.logo' and 'navItem'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
   61:40  warning  React Hook React.useEffect has a missing dependency: 'refreshUser'. Either include it or remove the dependency array                   react-hooks/exhaustive-deps
  143:6   warning  React Hook React.useMemo has missing dependencies: 'mkRouteProps' and 'oeqRoutes'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/settings/AdminDownloadDialog.tsx
  30:26  warning  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/theme/ColorPickerComponent.tsx
  41:3  warning  Useless constructor  @typescript-eslint/no-useless-constructor

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/theme/ThemePage.tsx
  210:33  warning  Expected '!==' and instead saw '!='  eqeqeq
  226:24  warning  Expected '!==' and instead saw '!='  eqeqeq

/home/developer/projects/OpenSource/openEquella/Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
  56:21  warning  Expected '!==' and instead saw '!='  eqeqeq

✖ 49 problems (0 errors, 49 warnings)
```

a few warnings, but no errors that would block the build

**Comment by ChristianMurphy** [comment]
@edalex-ian Travis is happy, CodeBuild is not, is the CodeBuild fail a false positive? Or are there some tests which still only run on that environment?

**Comment by PenghaiZhang** [comment]
> @edalex-ian Travis is happy, CodeBuild is not, is the CodeBuild fail a false positive? Or are there some tests which still only run on that environment?

Hi @ChristianMurphy , PR #1542 aims to make CodeBuild happy again.

**Comment by edalex-ian** [comment]
I thought they should both run the same tests, so that is kind of interesting - should maybe check. But let's just get the green over on #1542 and merge that into develop. Then let's merge develop into here. And then surely we can get this on into develop. Surely. :+1:

**Comment by ChristianMurphy** [comment]
rebased on #1542

**Pull request merged**
