### PR TITLE
Release/2020.1.0 chore/update tomcat to 8 5 51

### PR DESCRIPTION
**Pull request by cbeach47**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
No-effective change to tomcat AJP connector to work with Tomcat 8.5.51.  This disables the mandatory secret for AJP connections.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by cbeach47** [comment]
@PenghaiZhang / @edalex-ian / @SammyIsConfused - could one of you kick the CodeBuild env please?  Unfortunately, I don't have insight into what the issue is.  I've restarted the failures in Travis.

**Comment by PenghaiZhang** [comment]
> @PenghaiZhang / @edalex-ian / @SammyIsConfused - could one of you kick the CodeBuild env please? Unfortunately, I don't have insight into what the issue is. I've restarted the failures in Travis.

Hi @cbeach47 , all tests were actually passed. The issue is failing to create a new docker image. I guess this may be due to the name of this branch.

**Comment by edalex-ian** [comment]
Ah yes, `release/` etc are kind of reserved names.

**Comment by cbeach47** [comment]
Thanks @PenghaiZhang for check.  I guess that reserved keyword on `release` makes sense.  for this PR, I'll go ahead and merge once Travis plays nice then.

**Pull request merged**
