### PR TITLE
fix: github action functional test with postgresql 11

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
In addressing the npm issues caused by the `oeq-ts-rest-api` module https://github.com/openequella/openEQUELLA/pull/4679 , we also found that versions below PostgreSQL 12 is causing some problems, leading to test failures. Therefore, to quickly fix the GitHub Actions, we have temporarily changed the database version from 10 to 12. This branch is now intended for investigating the exact issues caused by the database version.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Heya @edalex-yinzi 

When you get a chance, could you please update this branch with the latest from `develop` ? (Just in case anything has improved.)

**Comment by edalex-yinzi** [comment]
> Heya @edalex-yinzi
> 
> When you get a chance, could you please update this branch with the latest from `develop` ? (Just in case anything has improved.)

Develop merged.

**Comment by edalex-ian** [comment]
@edalex-yinzi could you please merge in `develop` again? Be keen to see if anything is improved. :crossed_fingers:

**Comment by edalex-ian** [comment]
The run after you merged in develop kind of failed the same way on `(true,11)` but was fine on `(false, 11)`. So I'm running again to see what gives.

**Pull request closed without merging**
