### PR TITLE
Add a wait to ApidocsTest - testLoginNoAccess

### PR DESCRIPTION
**Pull request by SammyIsConfused**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change
This test has been intermittently failing a fair bit this week. Non-reproducible without throttling my browser network speed, which highlighted to me that we need a wait.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by edalex-ian — COMMENTED** [review]
Change looks good. After each completed GHA run, could you please run it again for 5 times and make a comment each to say what the outcome was? If we can get to 5 without it happening, then I reckon we can merge.

**Comment by SammyIsConfused** [comment]
Run 1: HierarchyTopicTest - childInheritance failed. ApidocsTest is fine. 
image

**Comment by SammyIsConfused** [comment]
Run 2: green build.

**Comment by SammyIsConfused** [comment]
Run 3: green build.

**Comment by SammyIsConfused** [comment]
Run 4: Green build.

**Comment by SammyIsConfused** [comment]
That's 5 green builds. Merging.

**Pull request merged**
