### PR TITLE
Add a script to initialise the Postgres used in Docker compose.

### PR DESCRIPTION
**Pull request by PenghaiZhang**
#2474 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds a script which is used by Docker-compose to initialise the database.

### CODE REVIEW

**Comment by edalex-ian** [comment]
Hmmmm, is this all necessary. I've only looked quickly, so perhaps I've missed something. But....

The standard postgres image works such that by default it will create a database matching the username specified in POSTGRES_USERNAME. For full options, see the options documented at https://hub.docker.com/_/postgres

So I'm thinking you don't need a script. Just different env vars... But maybe I'm missing something? :confused:

**Comment by PenghaiZhang** [comment]
> Hmmmm, is this all necessary. I've only looked quickly, so perhaps I've missed something. But....
> 
> The standard postgres image works such that by default it will create a database matching the username specified in POSTGRES_USERNAME. For full options, see the options documented at https://hub.docker.com/_/postgres
> 
> So I'm thinking you don't need a script. Just different env vars... But maybe I'm missing something?

That is exactly the page I was looking. And in that page, there is a section about `Initialization scripts`. I will try the approach you mentioned :smile:

**Comment by edalex-ian** [comment]
Yup, the init scripts are more so for non-standard activities. Like setting up schemas, data and/or custom permissions/db settings. But username/password/DB is run of the mill.

**Review by edalex-ian — APPROVED** [review]
LGTM. I guess we just need @cbeach47 to pull it down and see if it solves the issue.

**Review by cbeach47 — COMMENTED** [review]
Hmmm.

Running it with the defaults doesn't have the database auth errors (good), but oEQ doesn't come up.  Traefik shows the oeq, zk, and db nodes running.  

I try to hit http://localhost:8080/admin/ and get a 404.

I can access traefik via http://localhost:8080/dashboard/

Do you modify your defaults.xml, docker-compose.yml, or any other config file to get this to work?

Once it boots up, what URL do you access the server admin pages with?

**Comment by PenghaiZhang** [comment]
> Hmmm.
> 
> Running it with the defaults doesn't have the database auth errors (good), but oEQ doesn't come up. Traefik shows the oeq, zk, and db nodes running.
> 
> I try to hit http://localhost:8080/admin/ and get a 404.
> 
> I can access traefik via http://localhost:8080/dashboard/
> 
> Do you modify your defaults.xml, docker-compose.yml, or any other config file to get this to work?
> 
> Once it boots up, what URL do you access the server admin pages with?

Hi @cbeach47 , I use `oeq.localhost/admin/` to access the admin page.

**Comment by edalex-ian** [comment]
@PenghaiZhang , have you added an entry to your `/etc/hosts` file for  `oeq.localhost`?

**Comment by PenghaiZhang** [comment]
> @PenghaiZhang , have you added an entry to your `/etc/hosts` file for `oeq.localhost`?

No, I haven't. Do we need ? I think Traefik handles the request domain :thinking:

**Comment by edalex-ian** [comment]
Okay, I've tested this myself now and did run into a couple of bumps. Maybe it's because I'm on Debian rather than Ubuntu, but none the less I captured those tips by reworking README.md.

Further, so we're not trapped with version numbers in filenames, I tweaked the docker-compose.yml to simply using `equella-installer.zip`.

I think this is good to go. But perhaps we need one more person to take it for a spin. Would you have another chance @cbeach47 ? How about you @SammyIsConfused ?

**Comment by mrblippy** [comment]
I tried this out, all looks good. But i didn't have to edit my hosts file to access the oEQ instance using http://oeq.localhost

**Comment by SammyIsConfused** [comment]
Worked for me first go! Looks good. As with @mrblippy I didn't need to allow any hosts.

**Comment by edalex-ian** [comment]
I reckon you're good to merge this now @PenghaiZhang . No need to worry about the failing CI part - as this has no relationship to the CI steps.

**Comment by PenghaiZhang** [comment]
> I reckon you're good to merge this now @PenghaiZhang . No need to worry about the failing CI part - as this has no relationship to the CI steps.

Wonderful

**Pull request merged**
