### PR TITLE
chore: pin node version and npm version

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Pin Node and NPM versions so that Renovate will use the correct versions to build.

The pinned Node version matches to the one specified in `.nvmrc`.

### CODE REVIEW

**Review by edalex-ian — COMMENTED** [review]
Is it sufficient to only do `react-front-end/package.json`? I'd say we'd also at least want `oeq-ts-rest-api/package.json`. The others after that might be optional due to how little is in them and how little they're updated.

**Comment by PenghaiZhang** [comment]
> Is it sufficient to only do `react-front-end/package.json`? I'd say we'd also at least want `oeq-ts-rest-api/package.json`. The others after that might be optional due to how little is in them and how little they're updated.

Ah yeah thanks for reminding this! I have updated `oeq-ts-rest-api`.

**Review by edalex-ian — APPROVED** [review]
Looks good. It will be interesting to see if renovate also updates these values for us going forward. :thinking: :crossed_fingers:

**Comment by edalex-ian** [comment]
I wonder if when this merges several of the JS renovate PRs will suddenly go green and merge (after rebasing of course).

**Pull request merged**
