### PR TITLE
feat: code split index, only loading the components which are needed

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Goal: leverage https://reactjs.org/docs/code-splitting.html and https://parceljs.org/code_splitting.html to avoid loading all 3Mb of JavaScript on initial page load, instead load the files as needed

TODO:

- [x] Further codesplit IndexPage
- [x] Look into what PureScript is doing to the output
- [x] replace fragments as Suspense loader with a proper loader

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
The goal of this PR is to break the bundle down.
Removing pieces not needed where possible, and only loading the pieces needed for a specific page.
Here is how the bundle currently looks:

Screenshot_2020-06-12 entrybuild a2b47477 js - Source Map Explorer

**Comment by edalex-ian** [comment]
Heya @ChristianMurphy 

Definitely would be good if we achieved some good code splitting - especially when some of those large items will be rarely used in general cases.

How did you generate the image?

On the Purescript side, if it helps, keep in mind that there's only two parts left (in the componenent branch), and we hope to covert both maybe within the year. So if you can push those to the side... (If you wish to see what's left, best to have a glance at the current component/new_search_page branch.

**Comment by ChristianMurphy** [comment]
> How did you generate the image?

I used [source map explorer](https://www.npmjs.com/package/source-map-explorer)
and point it at the `entrybuild.{HASH}.js` file in *openEquella/Source/Plugins/Core/com.equella.core/js/target/resources/web/reactjs*

for example:
```
npx source-map-explorer entrybuild.a2b47477.js --no-border-checks
```

> On the Purescript side, if it helps, keep in mind that there's only two parts left (in the componenent branch), and we hope to covert both maybe within the year. So if you can push those to the side... (If you wish to see what's left, best to have a glance at the current component/new_search_page branch.

Thanks, I'll take a look

**Comment by edalex-ian** [comment]
With ideally the component branch merge happening today. This should be much more possible.

Indeed, we've already been able to use lazy loading on the component branch due to the removal of some of the PS.

**Comment by ChristianMurphy** [comment]
Excellent, redid the changes off of `develop` branch and force pushed over the existing branch.

**Comment by ChristianMurphy** [comment]
Thanks @edalex-ian that resolved several of the issues.
I think this is ready for review now.

It works and sets a good precedent, we may not get the full impact until the build supports code splitting, a build script (I think it is PS) is still taking all of the pieces and bundling the pieces into a single 8.2 Mb entry point.
Which even on a fast computer takes several seconds to download and parse.

**Comment by ChristianMurphy** [comment]
ed8c378 makes an immediate improvement to build size:

Before:
Screenshot_2020-10-15 entrybuild c110a7a9 js - Source Map Explorer

After:
Screenshot_2020-10-15 entrybuild 36b4ac98 js - Source Map Explorer

From 7.9 Mb to 3.4 Mb by explicitly telling parcel which icons to pull in (since it's tree shaker was failing).

**Comment by edalex-ian** [comment]
> [ed8c378](https://github.com/openequella/openEQUELLA/commit/ed8c3787f33dfa24d1fbcec8ee79c9e22304908e) makes an immediate improvement to build size:

Haaaawww! Nice work. I was aware from some other work the icons and Parcel needed some attention, just haven't had time. That's a great win!

I'll go and review the rest.

**Review by edalex-ian — APPROVED** [review]
LGTM! Nice work. :+1: 

Just one question. Did you do any manual testing for this. Of specific interest, is ensuring that the lazy load for the `SettingsPage` in `App.tsx` is still working fine in Legacy UI mode. (That's what it's all for.)

**Comment by edalex-ian** [comment]
The CodeBuild failure was the good ol' flaky `com.tle.webtests.test.searching.hierarchy.HierarchyTopicTest`. I've restarted that build.

**Comment by ChristianMurphy** [comment]
I smoke tested tested with
```html
<html><head></head><body><script>var themeSettings = {
    primaryColor: '#000',
    secondaryColor: '#000',
    backgroundColor: '#000',
    paperColor: '#000',
    menuItemColor: '#000',
    menuItemTextColor: '#000',
    menuItemIconColor: '#000',
    primaryTextColor: '#000',
    menuTextColor: '#000',
    fontSize: 12
  }</script> <div id="settingsPage"></div> <script src="entrybuild.36b4ac98.js"></script> </body></html>
```
it loads correctly, and gets are far as looking for legacy html elements on the page.

**Comment by ChristianMurphy** [comment]
Not sure what to make of this

```
FAILED: childInheritance
java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.tle.webtests.test.searching.hierarchy.HierarchyTopicTest.childInheritance(HierarchyTopicTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at de.johoop.testnginterface.TestNGInstance$.start(TestNGInstance.scala:60)
	at de.johoop.testnginterface.TestNGRunner.run(TestNGRunner.scala:45)
	at sbt.RunnerWrapper$1.runRunner2(FrameworkWrapper.java:230)
	at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:243)
	at sbt.TestRunner.runTest$1(TestFramework.scala:106)
	at sbt.TestRunner.run(TestFramework.scala:117)
	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
	at sbt.TestFunction.apply(TestFramework.scala:271)
	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:281)
	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
	at sbt.std.Transform$$anon$4.work(System.scala:66)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:272)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This PR doesn't modify the number of topics in search results.
Is this a false positive? Or is the error message misleading, and there is another issue?

**Comment by edalex-ian** [comment]
That was the same flaky one that failed on CodeBuild - which I now see is green. So I think if you rerun you'll be all green.

**Pull request merged**
