### PR TITLE
Setup CI with GitHub Actions

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included - kind of
- [ ] screenshots are included showing significant UI changes - NA
- [ ] documentation is changed or added - NA

##### Description of change

We continue to have issues with the reliability and speed of Travis builds - especially compared to the Edalex Codebuild builds. GitHub have recently introduced GitHub Actions and changed their pricing structure which means it's free for public repositories. Further, it has some compelling features which make it a better fit than Travis CI: single jobs can run for up to 6 hours, and a single workflow for up to 72 hours; more concurrent jobs (I think it's six); and storage for build artefacts - meaning community builds now stay in easy reach of the community.

As a result, this PR creats a GitHub Actions Workflow which is similar to the Travis build in that it will build the artefacts and then run the full test suite against the old and new UIs. And at the end, it simply publishes the artefacts against the workflow for easy downloading - no reliance on S3 etc. (It even publishes the Import Export Tools.) You can see the runs - and resultant artefacts - by clicking on the Actions tab for the repo: https://github.com/openequella/openEQUELLA/actions

This is my first use of GitHub Actions, so there's room for improvement. However it seems to be 'good enough' for now, and I'd love to start trailing it as part of the checks for all the builds to really compare against Travis.

In the future, areas for improvement could be:

- Looking at the list of [installed software](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) maybe we don't need to do the dance to install NVM - then also relying on the custom shell;
- Try to reduce some of the repetition with our own custom actions; and
- When we next prepare to do a release off `develop` we can look at adding in the publishing of a release with https://github.com/actions/create-release and https://github.com/actions/upload-release-asset

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Ah bugga! Need to include steps to support he work recently done on `develop` in 508699c25f43ba0fee61609b9eef8c1aae84b653

**Comment by ChristianMurphy** [comment]
> Ah bugga! Need to include steps to support he work recently done on develop in 508699c

Sorry :sweat_smile:

**Comment by ChristianMurphy** [comment]
> single jobs can run for up to 6 hours, and a single workflow for up to 72 hours; more concurrent jobs (I think it's six); and storage for build artefacts - meaning community builds now stay in easy reach of the community.

Excellent!
Another nicety I've come across it the build queue time often seems to be shorter than Travis CI, due to the higher concurrency for free plans ([Travis: 5 jobs](https://travis-ci.com/plans), [GH Actions: 20 jobs](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions))

> then also relying on the custom shell

The custom shell?
Was this needed for `nvm` or another tool?

**Comment by edalex-ian** [comment]
> Sorry :sweat_smile:

Nah, all good. It was my oversight. I really should've done a merge back in of develop, so thank you for doing that and confirming the build.

> The custom shell?
> Was this needed for nvm or another tool?

Yeah, just for the custom install of NVM (`bash -l` triggers the rc scripts/profiles and thereby allows the NVM start-up script to be sourced). But in theory NVM is available, however I thought early on I was finding that `nvm` resulted in command not found - will have to give it a whirl once all is settled.

**Pull request merged**
