### PR TITLE
Contribution wizard styling

### PR DESCRIPTION
**Pull request by mrblippy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes
wizard1
wizard2
wizard3
wizard4
wizard5
wizard6

##### Description of change

This covers the styling of (hopefully) everything in the contribution wizard, including moderation.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
image
The Child, Sibling, Remove and Initialise buttons are two narrow. Needs some padding so that the text doesn't get cut off.

**Comment by SammyIsConfused** [comment]
image
The "select thumbnails" dialog is strangely shaped.

**Comment by SammyIsConfused** [comment]
In the attachment control, if you click "Import files from scrapbook", this happens.
image

**Comment by SammyIsConfused** [comment]
The Edit File dialog styles are a bit wonky. 
image

**Comment by SammyIsConfused** [comment]
In an attachment control if you select "openEQUELLA Resource", this happens. 
image

**Comment by SammyIsConfused** [comment]
A lot of the dialogs for the options in a universal attachment control are strangely shaped in the same way. Namely, URLs, Web Pages, Google Books, Flickr, Youtube, iTunes U.
image

**Comment by SammyIsConfused** [comment]
The "reject task" dialog dropdown needs a min-width. 
image

**Comment by SammyIsConfused** [comment]
In IE11 specifically, the Add resource button is in the wrong place and has no icon. 
image

**Comment by mrblippy** [comment]
@SammyIsConfused all of these issues have been resolved, except for the issues related to the selection sessions. They should work properly once the selection session branch and this one have both been merged into the feature branch

**Comment by mrblippy** [comment]
@SammyIsConfused all of your issues have now been fixed. I am going to merge this back into the feature branch

**Pull request merged**
