### PR TITLE
chore(deps): Use group:definitelyTyped renovate preset

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

So as to reduce all the `@types` PRs.

See also: https://docs.renovatebot.com/presets-group/#groupdefinitelytyped

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Comment by ChristianMurphy** [comment]
Would we still want to split major version `@types` changes into their own PRs?

**Comment by edalex-ian** [comment]
> Would we still want to split major version `@types` changes into their own PRs?

Ooooh, good point @ChristianMurphy . Yes we would. I wonder how we achieve that. :thinking:

**Comment by ChristianMurphy** [comment]
:thinking: if we add (or already have) https://docs.renovatebot.com/presets-default/#separatemajorreleases it might just work :thinking:

**Comment by edalex-ian** [comment]
Well that's include in the `config:base` we use, so maybe I'll just merge and keep an eye on it. Hopefully I can remember this if an confusing ensues.

**Pull request merged**
