### PR TITLE
build: use 'node-version-file' to read '.nvmrc'

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

The GHA action `setup-node` now provides a property which is used to read `.nvmrc`. So update our CI config to use that.

### CODE REVIEW

**Comment by edalex-ian** [comment]
There we go, storybook failing as expected.

**Review by edalex-ian — APPROVED** [review]
Nice, that looks good @PenghaiZhang :bowing_man:

**Comment by edalex-ian** [comment]
Aha! And now `rest-module-testing` is failing as expected too:

```
FAIL test/Heartbeat.test.ts
  ● checkHeartBeat › returns a resolved promise if server responds correctly

    expect(received).resolves.toBeTruthy()

    Received promise rejected instead of resolved
    Rejected to value: [Error: connect ECONNREFUSED ::1:8080]

      21 | describe('checkHeartBeat', () => {
      22 |   it('returns a resolved promise if server responds correctly', async () => {
    > 23 |     await expect(checkHeartbeat(TC.API_PATH)).resolves.toBeTruthy();
         |           ^
      24 |   });
      25 | });
      26 |
```

I'm thinking that perhaps as part of this PR we should also revert 0c6dd7701ea80965312739cfa8c1d987393c065c. That should then produce a green build and then we can merge it in.

What do you think @PenghaiZhang ?

**Comment by PenghaiZhang** [comment]
> Aha! And now `rest-module-testing` is failing as expected too:
> 
> ```
> FAIL test/Heartbeat.test.ts
>   ● checkHeartBeat › returns a resolved promise if server responds correctly
> 
>     expect(received).resolves.toBeTruthy()
> 
>     Received promise rejected instead of resolved
>     Rejected to value: [Error: connect ECONNREFUSED ::1:8080]
> 
>       21 | describe('checkHeartBeat', () => {
>       22 |   it('returns a resolved promise if server responds correctly', async () => {
>     > 23 |     await expect(checkHeartbeat(TC.API_PATH)).resolves.toBeTruthy();
>          |           ^
>       24 |   });
>       25 | });
>       26 |
> ```
> 
> I'm thinking that perhaps as part of this PR we should also revert [0c6dd77](https://github.com/openequella/openEQUELLA/commit/0c6dd7701ea80965312739cfa8c1d987393c065c). That should then produce a green build and then we can merge it in.
> 
> What do you think @PenghaiZhang ?

I agree. And we can work on the node 18 update in another PR.

**Review by edalex-ian — APPROVED** [review]
LGTM!

**Comment by edalex-ian** [comment]
Okay, the build has already got past the pain points:

image

I'm going to merge.

**Pull request merged**
