### PR TITLE
fix(deps): update dependency eslint to v8

### PR DESCRIPTION
**Pull request by edalex-yinzi**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
This is a fix PR for upgrading eslint to v8, see previous attempts in: #3673  #3507
All the dependencies related/dependent on eslint v8 are also included in this PR:
- eslint-config-react-app #3672 
- typescript-eslint/eslint-plugin  #3531
- typescript-eslint/parser #3531
- eslint-plugin-flowtype #3519

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Interesting... I note the package-lock is updated in the `react-front-end` even though you didn't touch the `package.json` in there; however it's not updated in `oeq-rest-ts-api` event though you _did_ update the `package.json` in there... I think things are slightly muddled at the package-lock level.

**Comment by PenghaiZhang** [comment]
> Interesting... I note the package-lock is updated in the `react-front-end` even though you didn't touch the `package.json` in there; however it's not updated in `oeq-rest-ts-api` event though you _did_ update the `package.json` in there... I think things are slightly muddled at the package-lock level.

I expect to see a package-lock update in `oeq-rest-ts-api`, not in  `react-front-end` .

**Comment by edalex-ian** [comment]
Exactly, for this update I'd expect to see exactly four files updated:

- package.json
- package-lock.json
- oeq-ts-rest-api/package.json
- oeq-ts-rest-api/package-lock.json

(And that's because oeq-ts-rest-api looks after it's own linting for the day it becomes a stand-alone module.)

**Review by edalex-ian — APPROVED** [review]
There we go, now it's looking good. Let's hope it's all green. :wink:

**Comment by edalex-ian** [comment]
Doesn't come into play for the functional tests, already done it's job, so I'll merge now. :wink:

**Pull request merged**
