### PR TITLE
Update Swagger version to 1.6.2

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Update Swagger to make `apidocs.do` work properly.

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
I am curious why Renovate Bot does not update this :thinking: . 1.6.2 has been released for several days

**Comment by ChristianMurphy** [comment]
same as https://github.com/openequella/openEQUELLA/pull/1996 ?

**Comment by PenghaiZhang** [comment]
> same as #1996 ?

oops I did not realise we already have a PR for that...but not sure why builds failed. I will close this one.

**Comment by ChristianMurphy** [comment]
Either PR works, the renovate one seems to have picked up two (potential unrelated changes), it might take some work to get that one running.
If the issue persists, let's merge this PR instead.

**Comment by ChristianMurphy** [comment]
#1996 is blocked by https://github.com/renovatebot/renovate/issues/6723 let's go ahead with this PR.

**Comment by PenghaiZhang** [comment]
> #1996 is blocked by [renovatebot/renovate#6723](https://github.com/renovatebot/renovate/issues/6723) let's go ahead with this PR.

Cool. Once builds are green I will merge it.

**Pull request merged**
