### PR TITLE
Feature/update MUI to version 5

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Update MUI to version 5.

Known issues or todos:

* `Template.tsx` still uses the old `makeStyles`.
* `@material/picker` is not updated to the latest version. It must get updated otherwise it will break the whole new Search UI styles.
* The background colour in any legacy page is white rather than `#fafafa`. In Selection Session, the colour becomes transparent.
* Opening new Search UI triggers an error of `setAdornStart is not a function`. (Doing a `npm run dev` seems to fix it though). This is why `NewSearchPageTest` fails on CI.
* In new Search UI Gallery mode, the vertical gap between each tile is inconsistent with the horizontal gap

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
Looks like after the update, Jest test timeout happens randomly.

**Comment by edalex-ian** [comment]
Removed stale so we can keep this open just for a little longer.

**Comment by edalex-ian** [comment]
Latest code now merged in.

Same issues remain, and maybe some new ones - like in the new My Resources page when you click on the 'status' drop down, the whole background goes white (event menu etc) and some alignment goes askew. But then all returns once you make a selection. :shrug: 

Anyway, next step is to work to assess what remains and then progress.

**Comment by edalex-ian** [comment]
Curious, why has it not started a build. I wonder if 'Draft' PRs don't get built anymore. :thinking:

**Comment by edalex-ian** [comment]
Okay, if there are any conflicts on a merge then the PR does not start. Conflicts resolved, build commencing.

**Comment by edalex-ian** [comment]
Well of all the possible issues, this one was not expected:

```
> check:license
> cd react-front-end && licensee --production --errors-only && cd -

caniuse-lite@1.0.30001406
  NOT APPROVED
  Terms: CC-BY-4.0
  Repository: browserslist/caniuse-lite
  Homepage: None listed
  Author: Ben Briggs <beneb.info@gmail.com> (http://beneb.info/)
  Contributors: None listed

ERROR: "check:license" exited with 1.
```

I guess somewhere in the tangle of `package-lock.json` updates something has move to a new version of caniuse-lite which has a license we don't really accept. :disappointed:

**Pull request merged**
