### PR TITLE
test: remove the redundant staleness waiting in test case testDateVal…

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

`CALBookActivationTest` has been failing quite frequently due to an redundant wait of staleness. So I removed that wait and tested locally. Now let's see whether GHA will be happy with that.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
First time all good. Now try second time.

**Comment by edalex-yinzi** [comment]
Second time all good. Now try third time.

**Comment by edalex-yinzi** [comment]
testEditNavigation faield

**Comment by edalex-yinzi** [comment]
Fixed. Try fourth time.

**Comment by PenghaiZhang** [comment]
> Fixed. Try fourth time.

Thanks Yinzi! Looks like the CAL test is stable now.

**Review by edalex-ian — APPROVED** [review]
Looks pretty happy! GTG!

**Pull request merged**
