### PR TITLE
chore: drop Tokenisation REST endpoint

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Drop previously implemented tokenisation related code.

### CODE REVIEW

**Review by edalex-ian — COMMENTED** [review]
So close.

**Review by edalex-ian — APPROVED** [review]
Yeah, that should do it. :crossed_fingers: 

If it goes green, merge on. :wink:

**Comment by edalex-ian** [comment]
Hmmmm, Codebuild failed on `Search2ApiAdditionalTest` - but GHA failed on known flaky `LDAPTest` and `AdvancedScriptControlTest`. Do we need to worry about the Codebuild one @PenghaiZhang ?

**Comment by PenghaiZhang** [comment]
> Hmmmm, Codebuild failed on `Search2ApiAdditionalTest` - but GHA failed on known flaky `LDAPTest` and `AdvancedScriptControlTest`. Do we need to worry about the Codebuild one @PenghaiZhang ?

Let me retry Codebuild once.

**Comment by edalex-ian** [comment]
Did it again. Strange only on Codebuild. :thinking:

**Comment by PenghaiZhang** [comment]
> Did it again. Strange only on Codebuild. thinking

possibly like last time - another test creates an Item. 

I have added a couple `println` to check.

**Review by edalex-ian — APPROVED** [review]

**Pull request merged**
