### PR TITLE
Bugfix/1093 wizard sync backport 2018.2

### PR DESCRIPTION
**Pull request by abidingotter**
Surprisingly this backport of several of Jolse's fixes into 2018.2 appears to work without any issues.  Will see what the build says.

#1093

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
Looks good! Seems like the places modified were the same in 2018.2 so I'm fairly happy for this to go through.

**Comment by edalex-ian** [comment]
Just because there was some concern about this, @SammyIsConfused would you be able to download the installer from this successful build and give it a quick manual sanity test. If all is well then let's merge.

**Comment by SammyIsConfused** [comment]
@edalex-ian Tested from installer zip with the original test case from #1093. Works fine, the uuids are not carried over to the new attachment. We should be good to merge this in.

**Comment by edalex-ian** [comment]
Cool, sounds good. Thank you. :)

@PenghaiZhang once you've finished your other work on the `stable-2018.2` branch, do you want to merge this?

**Pull request merged**
