### PR TITLE
Add CircularProgress spinner to LegacyPage

### PR DESCRIPTION
**Pull request by mrblippy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes

##### Description of change

https://github.com/openequella/openEQUELLA/issues/1306

legacyspinner

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by mrblippy** [comment]
> <Grid container direction="column" justify="center" alignItems="center">
>    <Grid item><CircularProgress/></Grid>
> </Grid>

Yeah, that's very true

**Comment by PenghaiZhang** [comment]
When I open the logon page or when I logout I can see this spinner as well. Is that also what we want ?

**Comment by PenghaiZhang** [comment]
Another thing I noted is when I navigate from New UI to Legacy pages the title bar, for example, from Search to Contribute, the title on AppBar show `Search` until Contribute page is open. Would it be better to show `Contribute` while the spinner is displayed?

**Comment by PenghaiZhang** [comment]
> Another thing I noted is when I navigate from New UI to Legacy pages the title bar, for example, from Search to Contribute, the title on AppBar is `Search` until Contribute page is open. Would it be better to show `Contribute` while the spinner is displayed?

OK after a quick look I think this would be hard to achieve because `title` is part of  `content`. So we don't know what `title` would be until we get `content` .

**Comment by mrblippy** [comment]
> > Another thing I noted is when I navigate from New UI to Legacy pages the title bar, for example, from Search to Contribute, the title on AppBar is `Search` until Contribute page is open. Would it be better to show `Contribute` while the spinner is displayed?
> 
> OK after a quick look I think this would be hard to achieve because `title` is part of `content`. So we don't know what `title` would be until we get `content` .

Yeah, that might be out of the scope of this ticket. It feels like a 'nice to have' feature, as opposed to essential

**Comment by mrblippy** [comment]
> When I open the logon page or when I logout I can see this spinner as well. Is that also what we want ?

Hmm, I haven't visited the login page since implementing this spinner. I will take a look to see how it looks

**Comment by mrblippy** [comment]
> > When I open the logon page or when I logout I can see this spinner as well. Is that also what we want ?
> 
> Hmm, I haven't visited the login page since implementing this spinner. I will take a look to see how it looks

Yeah, i think this is fine

**Pull request merged**
