### PR TITLE
Rename custom upload headers for better compatibility with frontend proxies

### PR DESCRIPTION
**Pull request by doolse**
#1118 
Targeted towards `develop` as there are workarounds available.

99.9% of the javascript changes are due to the prettier formatting them for the first time.

### CODE REVIEW

**Comment by abidingotter** [comment]
@doolse Given that this is just nginx blocking perfectly valid headers, and that this will break any existing scripts reading the underscore value, should this be enabled by (dare I say it?) another config value?

**Comment by doolse** [comment]
> @doolse Given that this is just nginx blocking perfectly valid headers, and that this will break any existing scripts reading the underscore value, should this be enabled by (dare I say it?) another config value?

Where would a script be using these values?

**Comment by abidingotter** [comment]
> Where would a script be using these values?

They probably aren't, given it's undocumented.

**Comment by abidingotter** [comment]
Let's squerge after 2019.2

**Pull request closed without merging**
