### PR TITLE
chore(deps): Remove redux type dependencies

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

I don't think we have any redux code left, so might as well get rid of
the type dependencies so that renovate doesn't keep updating them.

However using `npm uninstall` has probably obfiscated what I removed as it seems quite a few deps were out of sort order. So I removed:

- @types/react-redux
- @types/redux-logger

If anything else is detected, then something went wrong.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Gah, was just meant to be a simple quick tweak. Works fine for me, might need you @PenghaiZhang to pull down the branch and see what it does on your machine. :thinking: 

(I have upgraded my NPM recently, so.....)

**Comment by edalex-ian** [comment]
Running build again just in case, as all is finally locally - even after removing all node_modules dirs etc.

Node versions:

```
$ node -v
v14.17.3
$ npm -v
7.19.1
```

**Comment by edalex-ian** [comment]
Okay, confirmed issue is due to NPM version. Will look into upgrading NPM on the build platforms to 7.x

**Review by ChristianMurphy — APPROVED** [review]

**Comment by ChristianMurphy** [comment]
> Okay, confirmed issue is due to NPM version. Will look into upgrading NPM on the build platforms to 7.x

I believe Node 16 ([soon to be the LTS release](https://github.com/nodejs/Release#release-schedule)) comes with npm 7 by default

**Comment by edalex-ian** [comment]
Ah! I didn't realise 16 was out. Well, that'll be an easy way to do it. I'll take that for a spin and see if the build and tests work with it. :crossed_fingers:

**Comment by edalex-ian** [comment]
Interesting, 1 jest SearchPage test failed. But all is finally locally. Will re-run.

**Comment by edalex-ian** [comment]
Okay, so next run that all worked fine but then `rest-module-testing` failed. Mind you though, all the other functional tests passed, so in theory it should be fine (as this change has nothing to do with the REST module.

**Pull request merged**
