### PR TITLE
Fix support for CsvList params in SearchFacets

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change

An incorrect assumption was made back in 861e4b1, and due to a missing test didn't realise this broke `searchItems`. So this PR reverts 861e4b1 and does it differently, as well as adding a test of `searchItems` for the missing coverage. (Although it looks like we could do with a fair bit more testing there.)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by SammyIsConfused — APPROVED** [review]

**Comment by SammyIsConfused** [comment]
Looks like you might need to run format:ts?

**Comment by edalex-ian** [comment]
Nah. `component/new-search-page` is currently not building due to new ESLint rules from merging in `develop`. @mrblippy is on it now.

We'll need to wait until we get a green build on `component/new-search-page`, then I'll merge that into here and have to wait for green here.

**Review by PenghaiZhang — APPROVED** [review]
Looks good to me!

**Comment by edalex-ian** [comment]
What!? Scalacheck tests failed with:

```
[info] ! BulkItemOps.run bulk ops: Exception raised on property evaluation.
[info] > ARG_0: List(RunBulkOp(List(pilot solutions immaculate, honeybunch, carracci sypher loleta hierodulic miscreative, area friend, pilot dogfood tense recentralizing undarned, carracci blatantly ophorectomize socotran eggshell, chekhovian crimping horse chekhovian, undarned, velour carracci chekhovian, davout tense crimping tallyman loleta),NoParamOp(removeWorkflow)), RunBulkOp(List(friend area plerp nonirrigable purana, ostracism preventoria gesellschaft plerp, ophorectomize juru),ResetToTask(Step 3,carracci scope nerpa)))
[info] > Exception: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
[info]   (chrome not reachable)
[info]   (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

That's got nothing to do with this. I see codebuild is happy, so I'll take that as a pass for the New UI mode. I'll just wait on GHA to pass on legacy UI.

Need to get this merged, so.....

**Comment by edalex-ian** [comment]
Okay, that's close enough for this. Merging.

**Pull request merged**
