### PR TITLE
build(gha): use ubuntu-latest for functional-tests

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

We are currently having memory issues, but on other branches where we use ubuntu-latest things are working. So this is a test.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by PenghaiZhang — APPROVED** [review]
LGTM.

**Comment by edalex-ian** [comment]
Well that's promising:

image

I'll do it one more time to be sure. ;)

**Comment by edalex-ian** [comment]
It's looking pretty good, but I'm running one more time (run #4) as the scalacheck tests keep failing - just one here and there. :confused:

**Comment by edalex-ian** [comment]
Although ScalaCheck still failing, at least we get the old-ui build on GHA alongside the new-ui on CodeBuild. So it seems an improvement. Will merge for now.

**Pull request merged**
