### PR TITLE
Redirect to Item by React Router

### PR DESCRIPTION
**Pull request by PenghaiZhang**
#1306 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Using a hyperlink to open Item Summary page results in reloading the whole page, so we instead use `Link` provided by react-router to avoid reloading whole page. Also include an Item's version in Search result so that client can generate the correct path for viewing each item.

### CODE REVIEW

**Comment by edalex-ian** [comment]
Whoops, you broke the types there @PenghaiZhang 

We really should incorporate that check as part of our build. That way devs can simply do an `sbt installerZip` and if that passes be confident all is in order.

**Comment by edalex-ian** [comment]
Still broken. May be a good idea to run the following locally:

```
npm run check:ts-types-source
```

**Comment by PenghaiZhang** [comment]
> Still broken. May be a good idea to run the following locally:
> 
> ```
> npm run check:ts-types-source
> ```

Thanks for reminding this check @edalex-ian !! I have run it locally and fixed all type issues this check found.

**Comment by edalex-ian** [comment]
GHA is just a flaky test failure: com.tle.webtests.test.contribute.controls.asc.AdvancedScriptControlTests

Strange CodeBuild is still not done. Maybe someone restarted it?

**Comment by PenghaiZhang** [comment]
> GHA is just a flaky test failure: com.tle.webtests.test.contribute.controls.asc.AdvancedScriptControlTests
> 
> Strange CodeBuild is still not done. Maybe someone restarted it?

I did not :laughing:

**Comment by edalex-ian** [comment]
Seems CodeBuild has 'failed, but also on the ASC test.

**Comment by PenghaiZhang** [comment]
All builds are green :smile:

**Comment by edalex-ian** [comment]
Good stuff. Merge on! :+1:

**Pull request merged**
