### PR TITLE
chore: configure renovate to update lockfiles weekly

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

One possible answer for https://github.com/openequella/openEQUELLA/pull/2061#issuecomment-659739319
documented at https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
E2E test for preset: https://github.com/renovatebot/renovate/blob/02e6817fb977ba82c13ce076759dbe179c37265d/test/e2e/package.json#L16

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
would address #2061, #2062, #2063, and #2068

**Comment by ChristianMurphy** [comment]
> I'm not entirely sure about this (stability wise),

Can you expand on your concern?

Would a monthly schedule offer more stability?
Is this something to discuss next CDM?

**Comment by edalex-ian** [comment]
> > I'm not entirely sure about this (stability wise),
> 
> Can you expand on your concern?
> 
> Would a monthly schedule offer more stability?
> Is this something to discuss next CDM?

Oh, just that the package-lock.json and the NPM ecosystem feels like a bit of rats nest at times. So the idea of suddenly updating a whole bunch of transitive dependencies in that context sounds like it could deliver a good number of unknowns - even if our test suite passes. (Recent experience too of TinyMCE and Swagger UI was interesting.)

But hey, I have nothing concrete to say this will hurt, and it is on the `develop` branch - and at least our maintenance branches will be static. Hence, I'm happy to try it while we're so far out from a release still. (No need to wait for CDM.)

Ooooh, Monthly does sound preferable. Let's do that.

**Comment by ChristianMurphy** [comment]
updated to Monthly schedule

**Pull request merged**
