### PR TITLE
test: jest 26

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change

Updates jest to version 26, refactors async tests to use async await.
https://jestjs.io/blog/2020/05/05/jest-26

:notebook: ts-jest 25 appears to work for oEQs Jest 26 needs, a version that officially supports Jest 26 is in the works https://github.com/kulshekhar/ts-jest/issues/1595

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
When I setup the REST Client and got the warning about this I decided to avoid it and wait - err on the side of caution. However, from looking at the ts-jest repo and milestones it looks as though it should be released in the next day or so / by end of the week.

Unfortunately the REST Client tests are not yet part of the CI, so I'll need to pull this branch and run them manually to make sure everything is still happy there too.

**Comment by edalex-ian** [comment]
ts-jest 26 is now out: https://www.npmjs.com/package/ts-jest/v/26.0.0

**Comment by ChristianMurphy** [comment]
Thanks for the ping @edalex-ian, rebased and updated ts-jest

**Comment by ChristianMurphy** [comment]
@edalex-ian it should and to be extra sure, added `eslint-plugin-jest` to verify this, and addressed the errors in 5aa6b9a

**Pull request merged**
