### PR TITLE
chore: update GHA configuration for OauthTest

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Add the configuration required for running OauthTest.

### CODE REVIEW

**Review by edalex-ian — APPROVED** [review]
LGTM!

**Comment by PenghaiZhang** [comment]
OauthTest is happy now, so I will merge once all jobs are finished.

**Comment by PenghaiZhang** [comment]
OauthTest failed again...but only on Old UI

>[TestNG] INVOKING: "OneAfterAnother" - com.tle.webtests.test.webservices.rest.OAuthTest.testOAuthTokenRevocation()
java.lang.AssertionError: expected:<403> but was:<200>

**Comment by edalex-ian** [comment]
> OauthTest failed again...but only on Old UI
> 
> > [TestNG] INVOKING: "OneAfterAnother" - com.tle.webtests.test.webservices.rest.OAuthTest.testOAuthTokenRevocation()
> > java.lang.AssertionError: expected:<403> but was:<200>

Intresting. I wonder if it takes a moment to remove the token from cache. :thinking:

**Comment by PenghaiZhang** [comment]
Oh dear I cannot believe `PortalsTest` failed 4 times in this PR...

**Comment by PenghaiZhang** [comment]
`PortalsTest` is failing in every testing job for Old UI. So merge this one and open another to fix PortalsTest.

**Comment by PenghaiZhang** [comment]
> > OauthTest failed again...but only on Old UI
> > > [TestNG] INVOKING: "OneAfterAnother" - com.tle.webtests.test.webservices.rest.OAuthTest.testOAuthTokenRevocation()
> > > java.lang.AssertionError: expected:<403> but was:<200>
> 
> Intresting. I wonder if it takes a moment to remove the token from cache. 🤔

Yeah possible. I will keep an eye on this one.

**Pull request merged**
