### PR TITLE
chore: setup Renovate dashboard issue feature

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change

https://renovate.whitesourcesoftware.com/blog/introducing-renovates-master-issue

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
Just tweaked title to try and [comply with doco](https://docs.renovatebot.com/reconfigure-renovate/) to trigger renovate check.

**Comment by ChristianMurphy** [comment]
I'm not sure renovate will add the tick, this PR was opened from a fork.
From the logs:
```
DEBUG: Found 1 Renovate PRs
{
  "renovatePrs": [
    {
      "number": 1530,
      "branchName": "chore/renovate-dashboard-issue",
      "sha": "58f19fe5daedf3dba83a0bd74f1f6b69e1a49e8d",
      "title": "chore: setup Renovate dashboard issue feature",
      "state": "open",
      "createdAt": "2020-03-07T19:07:28Z",
      "closed_at": null,
      "sourceRepo": "ChristianMurphy/openEquella"
    }
  ]
}
DEBUG: getPrFiles
{
  "prNo": 1530
}
DEBUG: PR has renovate files
{
  "prNo": 1530,
  "title": "chore: setup Renovate dashboard issue feature",
  "renovateFiles": [
    "renovate.json"
  ]
}
DEBUG: branch no longer exists - aborting
{
  "branchName": "58f19fe5daedf3dba83a0bd74f1f6b69e1a49e8d"
}
DEBUG: branch no longer exists - aborting
{
  "branchName": "chore/renovate-dashboard-issue"
}
DEBUG: Cannot access PR files to check them
```

https://app.renovatebot.com/dashboard#github/openequella/openEQUELLA/150332941

It looks like it doesn't lookup PRs opened from forks :disappointed: 

What I do know is that uPortal and uPortal-start have the same config option:
https://github.com/Jasig/uPortal/blob/4e81c7e27e580da9a371f3465da94e11d722b6e3/renovate.json#L5
https://github.com/Jasig/uPortal-start/blob/3d4a330f334450661ab8ce03cd3351e486980c62/renovate.json#L5
and it has worked in both cases.

**Comment by ChristianMurphy** [comment]
I could close this PR and re-open from a branch of `openequella/openEQUELLA`, rather than a branch of `ChristianMurphy/openEQUELLA` if you want

**Comment by edalex-ian** [comment]
Cool, not a problem then. I reckon let's merge it in then. :+1:

**Pull request merged**
