### PR TITLE
chore(checkstyle): Disable TODO check

### PR DESCRIPTION
**Pull request by edalex-ian**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

openEQUELLA seems to have a lot of historical TODO comments - about 202.
It'd be handy to keep them around as a form of documentation, as it
provides insight when trying to understand what's going on. Hopefully
code reviews though will stop people attempting to add new TODO
comments.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by edalex-ian** [comment]
That's just a flakey test failure - and this change has no bearing on tests.

**Review by PenghaiZhang — APPROVED** [review]
LGTM.

**Comment by edalex-ian** [comment]
Having merged #3006 and #3008 I'll update this branch to first solve the conflict, but that's all about the threshold. With #3008 now in that'll drop significantly again, so I'll fix as part of it. (Will do tomorrow.)

**Comment by edalex-ian** [comment]
Okay, that's done now in 79d89cf. Hopefully all is green and then we can merge. :wink:

**Pull request merged**
