### PR TITLE
Update TinyMCE to v6

### PR DESCRIPTION
**Pull request by SammyIsConfused**
##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
resolves #4041 

To upgrade to v6, we need to rework which plugins are added to TinyMCE since some were removed and some were renamed. 
I also removed the `@types/tinymce` dependency - this currently relates to TinyMCE v5 and so doesn't fit v6.
Aside from that, the major breaking change was to the `uploadHandler`. 
Previously the `images_upload_handler` option passed success or failure callbacks to report the status of an image upload. In TinyMCE v66, `images_upload_handler` reports upload results by returning a Promise.

The Login Notice Editor where TinyMCE is used has test coverage, so we don't need new ones. 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by SammyIsConfused** [comment]
Something went awry with the package-lock.json it seems. I'll fix that up

**Comment by SammyIsConfused** [comment]
Ha, interesting. `@types/tinymce` had `@types/jquery` as a dependency this whole time and that's what we've been relying on for jquery types across the frontend TS code. Added it explicitly, that should do it.

**Comment by edalex-ian** [comment]
There's probably just been some automerged renovate updates. So make sure you merge in `develop` to your branch.

**Review by edalex-ian — APPROVED** [review]
Thanks @SammyIsConfused

**Pull request merged**
