### PR TITLE
Hotfix/2019.1.2

### PR DESCRIPTION
**Pull request by PenghaiZhang**
##### Checklist

- [x] the [contributor license agreement] is signed
- [x] commit message follows [commit guidelines]

##### Description of change

Open a draft PR to check if anything is broken by commits cherry-picked into 2019.1.2

Fixes to be included are listed below:

- [x] Contribution wizard: List box width not correct when dynamically loaded #1200 
- [x] New UI: Add criteria button on Manage Resources page doesn't work on first click #1088 
- [x] Update oEQ version checking to using GitHub releases #1269 
- [x]  Advanced Search: Popup taxonomy browser doesn't work #1309
- [x]  Package Viewer: Error messages getting rendered with Side menu, header and footer #1198
- [x]  Attachment caching not functioning as expected #1181
- [x]  Can upload multiple attachments to attachment controls that don't allow multiple attachments #985
- [x]  EQUELLA logs HTTP referrer incorrectly if HEAD method is issued in MS Edge #861
- [x]  Item and attachment view counts not working properly #1199

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
The fix for `Contribution wizard: List box width` is picked firstly.

**Comment by PenghaiZhang** [comment]
The fix for `advanced criteria button/page` is picked.

**Comment by PenghaiZhang** [comment]
The change of version checking is picked. Just two things to be noted here.
1. The change includes two commits, one for the major changes and the other one for the AWS buildspec file.
2. Because the `travis.yml` used in 2019.1.2 doesn't include those significant changes made on 2019.2, the 'Jest test` is removed from for `travis.yml`.

**Comment by SammyIsConfused** [comment]
image
#1200 tested and verified via installer zip.

**Comment by SammyIsConfused** [comment]
#1088 tested and verified via installer zip.

**Comment by SammyIsConfused** [comment]
image
#1269 seems to be working. @PenghaiZhang and I decided not to create dummy releases again to test the semantic version upgrade cases since that was recently tested and could add email subscriber noise, but I have proved that the release version data is getting pulled from GH rather than the version server.

**Comment by SammyIsConfused** [comment]
image
#1198 tested and verified via installer zip.

**Comment by SammyIsConfused** [comment]
#1181 does not seem to be fixed in this version. Two jpegs with the same name will not invalidate the cache. Have confirmed that max-age=0. Needs to be fixed up.

**Comment by SammyIsConfused** [comment]
image
#985 verified and tested via installer zip.

**Comment by SammyIsConfused** [comment]
image
#861 tested and verified with installer zip, MS Edge VM and Moodle VM.

**Comment by SammyIsConfused** [comment]
#1309 verified and tested with installer zip. 
image

**Comment by SammyIsConfused** [comment]
So I just finished testing the  hotfix/2019.1.2 installer. All of the bugfixes that went in function as expected - bar one.
Attachment caching not functioning as expected #1181 does not seem to be working, the caching works exactly the same as it did before we made changes. Note though that the mac-age is correctly set to 0 - which means, our fix doesn't quite work.

**Comment by SammyIsConfused** [comment]
Attachment caching #1181 fix tested at commit 384453b, works as intended. So long as that commit passed the build we should be ready to proceed with Hotfix/2019.1.2.

**Comment by PenghaiZhang** [comment]
The real change is at line 761 and others are made by Prettier...

**Comment by PenghaiZhang** [comment]
Hi @edalex-ian , can you please review this commit ? https://github.com/openequella/openEQUELLA/pull/1336/commits/384453bb9e621a87ca41fb7c3456e01e6b0de3a2

**Comment by SammyIsConfused** [comment]
Verified and tested #1199 via installer zip.

**Pull request closed without merging**
